### ISSUE TITLE
[Bug] NotFoundError and crash

### ISSUE THREAD

**Issue by botka4aet** [Yidadaa/ChatGPT-Next-Web#1542]
**Describe the bug**
При удалении последнего символа в строке происходит вылет

**To Reproduce**
1. Ввести несколько строк текста
2. Удалить последний символ в строке, используя Backspace
3. Ошибка

**Expected behavior**
Удаление последнего символа в строке

**Desktop (please complete the following information):**
 - OS: Win10 64
 - Google Chrome
 - 112.0.5615.140

**Additional Logs**
```
Oops, something went wrong!

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.</code><code>
    at p
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at https://localhost/_next/static/chunks/6168.49e32da294613723.js:8:2144
    at div
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at Suspense
    at LoadableComponent
    at div
    at div
    at div
    at div
    at div
    at eW (https://localhost/_next/static/chunks/4132.28a5dc19f6d1b7e5.js:1:24224)
    at Suspense
    at LoadableComponent
    at j (https://localhost/_next/static/chunks/2236-45d0dcb8147cb22b.js:27:5969)
    at A (https://localhost/_next/static/chunks/2236-45d0dcb8147cb22b.js:27:6827)
    at div
    at div
    at V (https://localhost/_next/static/chunks/app/page-ff6287cb97b635a2.js:1:25480)
    at L (https://localhost/_next/static/chunks/2236-45d0dcb8147cb22b.js:27:6245)
    at p (https://localhost/_next/static/chunks/2236-45d0dcb8147cb22b.js:27:591)
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at X (https://localhost/_next/static/chunks/app/page-ff6287cb97b635a2.js:1:26131)
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at g (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:20516)
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at t.RedirectBoundary (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:27890)
    at t.NotFoundBoundary (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:26442)
    at m (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:22247)
    at t.ErrorBoundary (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:15690)
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at t.default (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:18251)
    at body
    at html
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at t.RedirectBoundary (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:27890)
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at t.NotFoundBoundary (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:26442)
    at O (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:10216)
    at ak (https://localhost/_next/static/chunks/2443530c-7e994f9f7e04c603.js:9:70056)
    at t.ErrorBoundary (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:15690)
    at t.default (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:9689)
    at j (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:6275)
    at C
    at M (https://localhost/_next/static/chunks/4961-0f8489e607d0e844.js:1:6639)
```

**Comment by Yidadaa** [comment]
Эта проблема стабильно воспроизводится? Пожалуйста, предоставьте исходный текст сообщения об ошибке, обернув его в синтаксис блока кода.

**Comment by annian101** [comment]
是稳定的出现

**Comment by Anionex** [comment]
同样出现了这个问题，在输入框输入时发生
