### ISSUE TITLE
[Bug] 使用飞书App打开网页报错

### ISSUE THREAD

**Issue by hjt1997** [Yidadaa/ChatGPT-Next-Web#1632]
使用飞书App打开网页报错
均为最新版
`ChunkLoadError: Loading chunk 1829 failed.
(missing: https://chatgpt.nextweb.fun/_next/static/chunks/1829.2b8a8de495d86156.js)
    at Lazy
    at Suspense
    at LoadableComponent
    at div
    at div
    at div
    at div
    at div
    at eH (https://chatgpt.nextweb.fun/_next/static/chunks/6337.df6b36118f67125a.js:1:24254)
    at Suspense
    at LoadableComponent
    at _ (https://chatgpt.nextweb.fun/_next/static/chunks/3974-b2b4ef6f9569a85e.js:27:5955)
    at A (https://chatgpt.nextweb.fun/_next/static/chunks/3974-b2b4ef6f9569a85e.js:27:6817)
    at div
    at div
    at q (https://chatgpt.nextweb.fun/_next/static/chunks/app/page-37f230ee5546a9b3.js:1:30131)
    at L (https://chatgpt.nextweb.fun/_next/static/chunks/3974-b2b4ef6f9569a85e.js:27:6235)
    at p (https://chatgpt.nextweb.fun/_next/static/chunks/3974-b2b4ef6f9569a85e.js:27:581)
    at d (https://chatgpt.nextweb.fun/_next/static/chunks/app/page-37f230ee5546a9b3.js:1:18703)
    at Y (https://chatgpt.nextweb.fun/_next/static/chunks/app/page-37f230ee5546a9b3.js:1:30812)
    at O (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:19927)
    at i (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:29366)
    at c (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:29438)
    at a (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:27458)
    at P (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:21580)
    at i (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:16283)
    at m (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:18851)
    at g (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:19679)
    at a (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:31085)
    at E (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:21821)
    at body
    at html
    at i (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:29366)
    at c (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:29438)
    at u (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:27385)
    at a (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:27458)
    at S (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:9459)
    at a (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:15705)
    at i (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:16283)
    at T (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:13091)
    at T (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:4199)
    at C
    at M (https://chatgpt.nextweb.fun/_next/static/chunks/8139-af5382b63a3b4f9a.js:1:4571)`

**Comment by Yidadaa** [comment]
#1502
