### ISSUE TITLE
npm run dev 启动会报错

### ISSUE THREAD

**Issue by lmuiotctf** [Yidadaa/ChatGPT-Next-Web#18]
> chatgpt-next-web@1.1 dev
> cross-env COMMIT_ID=$(git rev-parse --short HEAD) next dev

'rev-parse' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn rev-parse ENOENT
    at notFoundError (C:\Users\里面\Desktop\biye\ChatGPT-Next-Web\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\里面\Desktop\biye\ChatGPT-Next-Web\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\里面\Desktop\biye\ChatGPT-Next-Web\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\里面\Desktop\biye\ChatGPT-Next-Web\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn rev-parse',
  path: 'rev-parse',
  spawnargs: [ '--short', 'HEAD)', 'next', 'dev' ]

**Comment by Yidadaa** [comment]
请先 npm install。

推荐使用 yarn：
```
yarn install && yarn dev
```

**Comment by lmuiotctf** [comment]
目前成功启动了，但是界面会报错
![image](https://user-images.githubusercontent.com/52068443/227581388-d07ec5ca-3f82-43c3-b150-bfc67b732c4b.png)
![image](https://user-images.githubusercontent.com/52068443/227581435-8731793b-6cb7-48ed-9bdc-d1abaf4d635a.png)

**Comment by lmuiotctf** [comment]
作者建议新增一个输入密码访问此站，防止太多人用

**Comment by lmuiotctf** [comment]
对的，目前存在报错，但是正常访问使用
