### ISSUE TITLE
[Bug] Error: Loading CSS chunk 3313 failed. (https://网址/_next/static/css/51b0b9d2311d2482.css)

### ISSUE THREAD

**Issue by xxhjkl** [Yidadaa/ChatGPT-Next-Web#1894]
docker版从0521升级到608以后，点设置或者点面具就报错。具体错误如下，重新部署可能镜像自动拉去了608还是这样的报错。

     Error: Loading CSS chunk 3313 failed. (https://网址/_next/static/css/51b0b9d2311d2482.css)
    at Lazy
    at Suspense
    at LoadableComponent
    at _ (https://网址/_next/static/chunks/7064-09e24ff0ad62e608.js:27:5950)
    at A (https://网址/_next/static/chunks/7064-09e24ff0ad62e608.js:27:6808)
    at div
    at div
    at K (https://网址/_next/static/chunks/app/page-04053e3886139052.js:1:30292)
    at L (https://网址/_next/static/chunks/7064-09e24ff0ad62e608.js:27:6226)
    at p (https://网址/_next/static/chunks/7064-09e24ff0ad62e608.js:27:591)
    at d (https://网址/_next/static/chunks/app/page-04053e3886139052.js:1:21210)
    at V (https://网址/_next/static/chunks/app/page-04053e3886139052.js:1:30973)
    at O (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:20224)
    at i (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:29930)
    at c (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:30012)
    at l (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:27999)
    at P (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:21868)
    at c (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:16506)
    at m (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:19091)
    at g (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:19970)
    at a (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:31739)
    at E (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:22118)
    at body
    at html
    at i (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:29930)
    at c (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:30012)
    at a (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:27888)
    at l (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:27999)
    at S (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:9463)
    at l (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:15875)
    at c (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:16506)
    at T (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:13104)
    at T (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:4209)
    at C
    at w (https://网址/_next/static/chunks/8139-8903dea55c3d062f.js:1:4581)

如果是点设置的话，错误会变成 Error: Loading CSS chunk 7195 failed

已经用隐身模式测试过了，隐身模式下可以复现。手机上的safari也可以复现。麻烦大佬排查一下是哪里出问题了

**Comment by Yidadaa** [comment]
合并 #1882
