### ISSUE TITLE
[Bug] 网页无法打开正常打开，发生错误，

### ISSUE THREAD

**Issue by Vipxiaoming** [Yidadaa/ChatGPT-Next-Web#2744]
Oops, something went wrong
ChunkLoadError: Loading chunk 3267 failed.(error: http://1ocalcloudserver.top/_next/static/chunks/3267.c70bd58e0c0fOfa2.js)
at Lazy
at Suspense
at LoadableConponent
at div
at div
at U(http://localcloudserver.tap/_next/static/chunks/app/page-815c8f1c3178c3f8.js:1:25603)
at div
at ] (http://localcloudserver.top/ next/static/chunks/app/page-815c8f1c3178c3f8.is:1:31281)top/_next/static/chunks/8855-58741da24604ff94.js:27:6239)at L(http://localcloudserver.at p (http://1ocalcloudserver.top/ next/static/chunks/8855-58741da24604ff94.is:27:591)at d (http://localcloudserver.top/_next/static/chunks/app/page-815c8f1c3178c3f8.js:1:19114)at Q (http://localcloudserver.top/_next/static/chunks/app/page-815c8f1c3178c3f8.js:1:32071at 0 (http://localcloudseryer.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:20224)top/ next/static/chunks/8139-8903dea55c3d062f.is:1:29930at i (http://localcloudservertop/_next/static/chunks/8139-8903dea55c3d062f.js:1:30012)at c (http://localcloudserver.at 1(http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:27999)at P (http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:21868top/_next/static/chunks/8139-8903dea55c3d062f.is:1:16506)at c(http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:19091)at m (http://localcloudserver.at g (http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:19970at a (http://1ocalcloudserver.top/_next/static/chunks/8139-8903dea55c3d062f.js:1:31739)at E (http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:22118
at bodyat html
at i (http://1ocalcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.js:1:29930)at c(http://1ocalcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:30012)at a (http://localcloudserver.top/_next/static/chunks/8139-8903dea55c3d062f.is:1:27888)at 1 (http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:27999at S (http://1ocalcloudserver.top/next/static/chunks/8139-8903dea55c3d062f.js:1:9463)top/_next/static/chunks/8139-8903dea55c3d062f.is:1:15875)at 1(http://localcloudserver.at c (http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:16506at T(http://1ocalcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.js:1:13104)at T(http://1ocalcloudserver.top/_next/static/chunks/8139-8903dea55c3d062f.js:1:4209)
at 
at w (http://localcloudserver.top/ next/static/chunks/8139-8903dea55c3d062f.is:1:4581)
![1](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120306492/702ecf4b-4d18-49bf-8e30-fe83d55d6c90)

**Comment by Yidadaa** [comment]
1. 尝试刷新浏览器
2. 浏览器存在兼容性问题，更新浏览器
3. 编译时增加一个环境变量，关闭分块编译：DISABLE_CHUNK=1

**Comment by haobarry** [comment]
一样的问题 不过是在回答问题的时候出现
