### ISSUE TITLE
[Bug] webDAV设置报错

### ISSUE THREAD

**Issue by hnsongbiao** [Yidadaa/ChatGPT-Next-Web#2852]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/10285955/7d1169eb-e33f-4962-8186-4ea0b7a9d4c3)
webDAV设置报错

7698-f08131f0571c774c.js:1  [WebDav] failed to check Error: [CORS Fetch] url must starts with http/https
    at r (page-98863b17a981a49b.js:1:196238)
    at Object.check (page-98863b17a981a49b.js:1:195102)
    at Object.check (page-98863b17a981a49b.js:1:191911)
    at l (670.12ad221ef2289cde.js:1:12693)
    at Object.l5 (bce60fc1-76a57db123ee8dbb.js:9:67335)
    at ar (bce60fc1-76a57db123ee8dbb.js:9:67489)
    at bce60fc1-76a57db123ee8dbb.js:9:133089
    at u2 (bce60fc1-76a57db123ee8dbb.js:9:133188)
    at u3 (bce60fc1-76a57db123ee8dbb.js:9:133602)
    at bce60fc1-76a57db123ee8dbb.js:9:139094
window.console.error @ 7698-f08131f0571c774c.js:1
check @ page-98863b17a981a49b.js:1
check @ page-98863b17a981a49b.js:1
l @ 670.12ad221ef2289cde.js:1
l5 @ bce60fc1-76a57db123ee8dbb.js:9
ar @ bce60fc1-76a57db123ee8dbb.js:9
(匿名) @ bce60fc1-76a57db123ee8dbb.js:9
u2 @ bce60fc1-76a57db123ee8dbb.js:9
u3 @ bce60fc1-76a57db123ee8dbb.js:9
(匿名) @ bce60fc1-76a57db123ee8dbb.js:9
oS @ bce60fc1-76a57db123ee8dbb.js:9
ir @ bce60fc1-76a57db123ee8dbb.js:9
u9 @ bce60fc1-76a57db123ee8dbb.js:9
i6 @ bce60fc1-76a57db123ee8dbb.js:9
i4 @ bce60fc1-76a57db123ee8dbb.js:9
7698-f08131f0571c774c.js:1  [WebDav] failed to check Error: [CORS Fetch] url must starts with http/https
    at r (page-98863b17a981a49b.js:1:196238)
    at Object.check (page-98863b17a981a49b.js:1:195102)
    at Object.check (page-98863b17a981a49b.js:1:191911)
    at l (670.12ad221ef2289cde.js:1:12693)
    at Object.l5 (bce60fc1-76a57db123ee8dbb.js:9:67335)
    at ar (bce60fc1-76a57db123ee8dbb.js:9:67489)
    at bce60fc1-76a57db123ee8dbb.js:9:133089
    at u2 (bce60fc1-76a57db123ee8dbb.js:9:133188)
    at u3 (bce60fc1-76a57db123ee8dbb.js:9:133602)
    at bce60fc1-76a57db123ee8dbb.js:9:139094
window.console.error @ 7698-f08131f0571c774c.js:1
check @ page-98863b17a981a49b.js:1
check @ page-98863b17a981a49b.js:1
l @ 670.12ad221ef2289cde.js:1
l5 @ bce60fc1-76a57db123ee8dbb.js:9
ar @ bce60fc1-76a57db123ee8dbb.js:9
(匿名) @ bce60fc1-76a57db123ee8dbb.js:9
u2 @ bce60fc1-76a57db123ee8dbb.js:9
u3 @ bce60fc1-76a57db123ee8dbb.js:9
(匿名) @ bce60fc1-76a57db123ee8dbb.js:9
oS @ bce60fc1-76a57db123ee8dbb.js:9
ir @ bce60fc1-76a57db123ee8dbb.js:9
u9 @ bce60fc1-76a57db123ee8dbb.js:9
i6 @ bce60fc1-76a57db123ee8dbb.js:9
i4 @ bce60fc1-76a57db123ee8dbb.js:9
7698-f08131f0571c774c.js:1  [WebDav] failed to check Error: [CORS Fetch] url must starts with http/https
    at r (page-98863b17a981a49b.js:1:196238)
    at Object.check (page-98863b17a981a49b.js:1:195102)
    at Object.check (page-98863b17a981a49b.js:1:191911)
    at l (670.12ad221ef2289cde.js:1:12693)
    at Object.l5 (bce60fc1-76a57db123ee8dbb.js:9:67335)
    at ar (bce60fc1-76a57db123ee8dbb.js:9:67489)
    at bce60fc1-76a57db123ee8dbb.js:9:133089
    at u2 (bce60fc1-76a57db123ee8dbb.js:9:133188)
    at u3 (bce60fc1-76a57db123ee8dbb.js:9:133602)
    at bce60fc1-76a57db123ee8dbb.js:9:139094
window.console.error @ 7698-f08131f0571c774c.js:1
check @ page-98863b17a981a49b.js:1
check @ page-98863b17a981a49b.js:1
l @ 670.12ad221ef2289cde.js:1
l5 @ bce60fc1-76a57db123ee8dbb.js:9
ar @ bce60fc1-76a57db123ee8dbb.js:9
(匿名) @ bce60fc1-76a57db123ee8dbb.js:9
u2 @ bce60fc1-76a57db123ee8dbb.js:9
u3 @ bce60fc1-76a57db123ee8dbb.js:9
(匿名) @ bce60fc1-76a57db123ee8dbb.js:9
oS @ bce60fc1-76a57db123ee8dbb.js:9
ir @ bce60fc1-76a57db123ee8dbb.js:9
u9 @ bce60fc1-76a57db123ee8dbb.js:9
i6 @ bce60fc1-76a57db123ee8dbb.js:9
i4 @ bce60fc1-76a57db123ee8dbb.js:9

**Comment by Yidadaa** [comment]
检查你填的 webdav 链接开头是不是有空格
