### ISSUE TITLE
意外报错  无法进入网页

### ISSUE THREAD

**Issue by haobarry** [Yidadaa/ChatGPT-Next-Web#3066]
**Describe the bug**
正在写问题的时候,或者ai在回答问题的时候, 网页突然崩溃 报错.
```
TypeError: this.data is undefined
nl@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:442997
4868/uy<@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:910875
div
uv@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:910937
Suspense
LoadableComponent
div
div
div
div
div
t2@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:109826
t3@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:120174
Suspense
LoadableComponent
C@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:177:3290
P@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:177:4721
div
div
$@https://aichat.gedadconns.com/_next/static/chunks/app/page-105230da3c143bbe.js:1:40753
N@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:177:4209
b@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:168:659
m@https://aichat.gedadconns.com/_next/static/chunks/app/page-105230da3c143bbe.js:1:27984
et@https://aichat.gedadconns.com/_next/static/chunks/app/page-105230da3c143bbe.js:1:41770
_@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:968564
l@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:978061
u@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:978146
s@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:976174
E@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:970121
u@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:964817
x@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:967377
k@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:968258
o@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:979872
S@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:970489
body
html
l@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:978061
u@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:978146
o@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:976019
s@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:976174
O@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:958876
s@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:964126
u@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:964817
N@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:962274
N@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:953799
D
I@https://aichat.gedadconns.com/_next/static/chunks/04b39fde-8773f5ca15a63838.js:96:954171
```

**To Reproduce**
使用vercel 创建的前端

**Additional Logs**
Add any logs about the problem here.

**Comment by haobarry** [comment]
有时候会报这个错无 ```TypeError: Cannot read properties of undefined (reading 'inTable')```

**Comment by Yidadaa** [comment]
版本？

**Comment by haobarry** [comment]
> 版本？

版本  2.98

**Comment by GithuBarry** [comment]
+1 
Version `v2.10.1`
而且有时候会错误log太长，导致`Clear All Data`button消失，得缩小网页缩放才能看到

```
TypeError: Cannot read properties of undefined (reading 'inTable')
    at ni (https://***.com/_next/static/chunks/1722.cca2ca1233935515.js:6:97139)
    at https://***.com/_next/static/chunks/1722.cca2ca1233935515.js:6:299553
    at div
    at ot (https://***.com/_next/static/chunks/1722.cca2ca1233935515.js:6:299909)
    at Suspense
    at LoadableComponent
    at div
    at div
    at div
    at div
    at div
    at ti (https://***.com/_next/static/chunks/2983.febdad1bd2c3e61d.js:1:44707)
    at tc (https://***.com/_next/static/chunks/2983.febdad1bd2c3e61d.js:1:55160)
    at Suspense
    at LoadableComponent
    at O (https://***.com/_next/static/chunks/2089-ec46ebde6b5eec54.js:28:3268)
    at j (https://***.com/_next/static/chunks/2089-ec46ebde6b5eec54.js:28:4707)
    at div
    at div
    at ee (https://***.com/_next/static/chunks/app/page-319a733ac0af0f77.js:1:49887)
    at P (https://***.com/_next/static/chunks/2089-ec46ebde6b5eec54.js:28:4125)
    at g (https://***.com/_next/static/chunks/2089-ec46ebde6b5eec54.js:19:627)
    at m (https://***.com/_next/static/chunks/app/page-319a733ac0af0f77.js:1:36462)
    at ea (https://***.com/_next/static/chunks/app/page-319a733ac0af0f77.js:1:50977)
    at m (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:21109)
    at l (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:32022)
    at i (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:32104)
    at u (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:28675)
    at a (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:28786)
    at O (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:22448)
    at s (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:17237)
    at v (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:19866)
    at g (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:20855)
    at u (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:35015)
    at P (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:22709)
    at body
    at html
    at l (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:32022)
    at i (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:32104)
    at w (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:10509)
    at l (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:16512)
    at s (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:17237)
    at C (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:14279)
    at j (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:4440)
    at C
    at w (https://***.com/_next/static/chunks/4938-2d6ff5f1bf6accd7.js:1:4809)
```

**My method to reproduce this error**: In a new chat with GPT4 1106, copy above error and prepend "How to deal with this:\n\n" and the error probably will occur in response.
<img width="918" alt="img" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/33831597/f4cc94ea-6366-4fc9-883b-6bcd494a7863">
