### ISSUE TITLE
[Bug] 运行本地部署脚本

### ISSUE THREAD

**Issue by 2478641181** [Yidadaa/ChatGPT-Next-Web#822]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch' imported from /root/ChatGPT-Next-Web/scripts/fetch-prompts.mjs
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ next start
/bin/sh: next: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**如何复现**
运行本地部署脚本

**截图**
![image](https://user-images.githubusercontent.com/92560664/232200511-0cecb1c1-7a44-4b77-9b48-64771ab6935a.png)

**一些必要的信息**
 - windows 11
 - 部署方式 服务器部署

**Comment by Yidadaa** [comment]
nodejs 版本太低了，升级到 16 以上。
